apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagebuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      name: imagebuilder
  template:
    metadata:
      labels:
        name: imagebuilder
    spec:
      serviceAccountName: imagebuilder
      containers:
        - name: imagebuilder
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - imagebuilder
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "imagebuilder"
