kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagebuilder
subjects:
- kind: ServiceAccount
  name: imagebuilder
roleRef:
  kind: Role
  name: imagebuilder
  apiGroup: rbac.authorization.k8s.io
